---
title: "final_project"
author: "Simona Rahi"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Loading and Preparation

```{r include=FALSE}
# loading libraries
library(dplyr)
library(fpp2)
library(forecast)
library(tseries)
library(kader)
```

```{r}
# loading dataset
df <- read.csv('retail_sales.csv')
```

```{r}
alc <- df %>% select(alcohol_sales)
sp <- df %>% select(sporting_goods_sales)
cloth <- df %>% select(clothing_sales)
furn <- df %>% select(furniture_sales)
rest <- df %>% select(restaurants_sales)
```

```{r}
alcohol <- ts(data = alc, start = c(1992,01), end = c(2020,08), frequency = 12)
sporting <- ts(data = sp, start = c(1992,01), end = c(2020,08), frequency = 12)
clothing <- ts(data = cloth, start = c(1992,01), end = c(2020,08), frequency = 12)
furniture <- ts(data = furn, start = c(1992,01), end = c(2020,08), frequency = 12)
restaurant <- ts(data = rest, start = c(1992,01), end = c(2020,08), frequency = 12)
```

## Clothing Sales 

#### Plotting and Observing

```{r}
autoplot(clothing, main = "U.S. Clothing Sales Between 1990 and 2020", ylab = "million dollars")
```

```{r}
ggseasonplot(clothing, year.labels=TRUE, year.labels.left=TRUE) +
  ylab("million dollars") +
  ggtitle("Seasonal plot: U.S. Clothing Sales")
```

```{r}
gglagplot(clothing, lags=24) + 
  ylab("U.S. Clothing Sales This Year") + xlab("Lagged Clothing Sales")
```

```{r}
cube.clothing <- kader:::cuberoot(clothing)
autoplot(cube.clothing, main = "Cube Root U.S Clothing Sales Between 1990 and 2020", ylab = "cuberoot sales in million dollars")
```

```{r}
stl.fit <- stl(ts(clothing), s.window=7, t.window=7)
autoplot(ts(stl.fit)) + xlab("Year") + ggtitle("STL Decomposition of Sqrt Monthly Clothing Retail Sales in the U.S")
```


#### ARIMA modeling

```{r}
ndiffs(cube.clothing)
ndiffs(cube.clothing, test = "adf")
```


```{r}
# taking seasonal difference to stabilize mean
diff.cloth <- diff(cube.clothing, lag = 12)
ggAcf(diff.cloth, main = "ACF plot after seasonal differencing")
ggAcf(cube.clothing, main = "ACF plot without seasonal differencing")
```

```{r}
# kpss testing stationarity
kpss.test(diff.cloth)
```

```{r}
tsdisplay(diff.cloth, main = "Seasonally Differenced Clothing Sales")
```

$y_t'=\theta_1y'_{t-1} + \theta_2y'_{t-2} + \theta_3y'_{t-3} +\epsilon_t,~~\epsilon_t\sim_{i.i.d}N(0,\sigma^2)$
  
  $y_t'=y_t-y_{t-12}$
  
```{r}
fit1 <- Arima(clothing, order=c(0,0,4), seasonal=c(0,1,0), lambda = 0.3)
summary(fit)
```

```{r}
checkresiduals(fit1)
```


```{r}
# neighboring models: ARIMA(0,0,5)(0,1,0) , ARIMA(0,0,3)(0,1,0) , ARIMA(1,0,4)(0,1,0) , ARIMA(0,0,4)(1,1,0) , ARIMA(0,0,4)(0,1,1)

allarima <- list(c(0,0,5,0,1,0),
                     c(0,0,3,0,1,0), 
                     c(1,0,4,0,1,0), 
                     c(0,0,4,1,1,0), 
                     c(0,0,4,0,1,1))

arima.all.aicc <- sapply(allarima,function(x) Arima(clothing, lambda=0.3, order=x[1:3], seasonal = x[4:6])$aicc)


clothing.train <- window(clothing,start=c(1992,1), end=c(2018,1))
clothing.test <- window(clothing, start=c(2018,2))

test.all.rmse <- c()
AICc <- c()

for (arima.param in allarima){
  arima.fit <- Arima(clothing.train,
                     lambda=0.3,
                     order=arima.param[1:3], 
                     seasonal=arima.param[4:6])
  test.all.rmse <- c(test.all.rmse, accuracy(forecast(arima.fit,24), clothing.test)[2,"RMSE"])
}

```

```{r}
arima.all.aicc
```

```{r}
test.all.rmse
```

```{r}
# ARIMA (1,0,4)(0,1,0)
winner.clothing <- Arima(clothing.train,
                     lambda=0.3,
                     order=c(1,0,4), 
                     seasonal=c(0,1,0))
checkresiduals(winner.clothing)
```


```{r}
# autoARIMA
fit.auto.clothing <- auto.arima(clothing, lambda=0.3)
summary(fit.auto.clothing)
```

```{r}
checkresiduals(fit.auto.clothing)
```

#### Forecasting

```{r}
autoplot(forecast(fit.auto.clothing),24)
```

